language: csharp
dotnet: 2.0.0

before_script:
 - yarn install
 - dotnet restore

script:
 - cd ./src
 - dotnet fable yarn-run build
 - cd ..
 - npm install netlify-cli -g
 - netlify deploy -t $NETLIFY_ACCESS_TOKEN
